 function dosomething() {
    console.log("Try and Catch Statement working")
 }

 try {
    dosomething();
 } catch (error) {
    console.log("Error Occured")
    console.log(error)
 }